#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Installs MultiTerminal integration for Claude Code (hooks + MCP servers)

.DESCRIPTION
    Automated installer for MultiTerminal Claude Code integration:
    - Deploys hooks (activity tracking, context injection)
    - Configures MCP servers (session history)
    - Auto-generates configuration with correct paths
    - Validates installation and dependencies

.PARAMETER InstallPath
    Installation directory for MultiTerminal. Defaults to script directory.

.PARAMETER SkipNodeModules
    Skip npm install for MCP servers (use if node_modules already exists)

.EXAMPLE
    .\Install-MultiTerminalIntegration.ps1

.EXAMPLE
    .\Install-MultiTerminalIntegration.ps1 -InstallPath "C:\Applications\MultiTerminal"
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$InstallPath = $PSScriptRoot,

    [Parameter()]
    [switch]$SkipNodeModules
)

$ErrorActionPreference = 'Stop'

Write-Host "=== MultiTerminal Claude Code Integration Installer ===" -ForegroundColor Cyan
Write-Host ""

# Resolve paths
$InstallPath = (Resolve-Path $InstallPath).Path
$ClaudeDir = Join-Path $env:USERPROFILE ".claude"
$HooksDir = Join-Path $ClaudeDir "hooks"
$McpServerDir = Join-Path $InstallPath "mcp-session-history"

Write-Host "Configuration:" -ForegroundColor Yellow
Write-Host "  Install Path: $InstallPath"
Write-Host "  Claude Dir:   $ClaudeDir"
Write-Host "  Hooks Dir:    $HooksDir"
Write-Host "  MCP Server:   $McpServerDir"
Write-Host ""

# === Step 1: Validate Prerequisites ===
Write-Host "[1/7] Validating prerequisites..." -ForegroundColor Green

# Check Node.js
try {
    $nodeVersion = node --version 2>$null
    Write-Host "  ✓ Node.js found: $nodeVersion" -ForegroundColor Green
} catch {
    Write-Error "Node.js not found. Install from https://nodejs.org/"
    exit 1
}

# Check npm
try {
    $npmVersion = npm --version 2>$null
    Write-Host "  ✓ npm found: v$npmVersion" -ForegroundColor Green
} catch {
    Write-Error "npm not found. Install Node.js from https://nodejs.org/"
    exit 1
}

# Check MCP server directory
if (-not (Test-Path $McpServerDir)) {
    Write-Error "MCP server directory not found: $McpServerDir"
    Write-Host "  Expected: $McpServerDir\index.js" -ForegroundColor Red
    exit 1
}
Write-Host "  ✓ MCP server found" -ForegroundColor Green

Write-Host ""

# === Step 2: Create directories ===
Write-Host "[2/7] Creating directories..." -ForegroundColor Green

if (-not (Test-Path $ClaudeDir)) {
    New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null
    Write-Host "  ✓ Created $ClaudeDir" -ForegroundColor Green
}

if (-not (Test-Path $HooksDir)) {
    New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
    Write-Host "  ✓ Created $HooksDir" -ForegroundColor Green
}

# Create multiterminal data directory
$DataDir = Join-Path $env:APPDATA "multiterminal"
if (-not (Test-Path $DataDir)) {
    New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
    Write-Host "  ✓ Created $DataDir" -ForegroundColor Green
}

Write-Host ""

# === Step 3: Install MCP server dependencies ===
if (-not $SkipNodeModules) {
    Write-Host "[3/7] Installing MCP server dependencies..." -ForegroundColor Green

    Push-Location $McpServerDir
    try {
        Write-Host "  Running: npm install" -ForegroundColor Gray
        npm install --silent 2>&1 | Out-Null

        # Verify better-sqlite3 installed
        $sqlite3Path = Join-Path $McpServerDir "node_modules\better-sqlite3"
        if (Test-Path $sqlite3Path) {
            Write-Host "  ✓ Dependencies installed successfully" -ForegroundColor Green
        } else {
            Write-Warning "  better-sqlite3 not found, but npm install completed"
        }
    } catch {
        Write-Error "Failed to install npm dependencies: $_"
        exit 1
    } finally {
        Pop-Location
    }
} else {
    Write-Host "[3/7] Skipping npm install (SkipNodeModules flag set)" -ForegroundColor Yellow
}

Write-Host ""

# === Step 4: Generate hook files with auto-resolved paths ===
Write-Host "[4/7] Generating hook files..." -ForegroundColor Green

# Escape backslashes for JavaScript strings
$sqlite3PathEscaped = $McpServerDir.Replace('\', '\\') + "\\node_modules\\better-sqlite3"

# activity-hook.js
$activityHookContent = @"
#!/usr/bin/env node
/**
 * Activity Recording Hook for Claude Code
 * Auto-generated by Install-MultiTerminalIntegration.ps1
 */

const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(process.env.APPDATA || '', 'multiterminal', 'multiterminal.db');

function requireBetterSqlite3() {
  const possiblePaths = [
    'better-sqlite3',
    '$sqlite3PathEscaped',
  ];

  for (const modulePath of possiblePaths) {
    try {
      return require(modulePath);
    } catch (e) {
      // Try next path
    }
  }
  return null;
}

const BUILD_PATTERNS = [
  { pattern: /dotnet\s+(build|publish|test|run)/i, type: 'dotnet' },
  { pattern: /msbuild/i, type: 'msbuild' },
  { pattern: /npm\s+(run\s+)?(build|test|start)/i, type: 'npm' },
  { pattern: /yarn\s+(build|test|start)/i, type: 'yarn' },
  { pattern: /go\s+(build|test|run)/i, type: 'go' },
  { pattern: /cargo\s+(build|test|run)/i, type: 'cargo' },
  { pattern: /pytest|python.*-m\s+pytest/i, type: 'pytest' },
  { pattern: /jest|vitest|mocha/i, type: 'test' },
];

const SKIP_TOOLS = new Set(['Read', 'Glob', 'Grep', 'ToolSearch']);

function recordActivity(activityType, actor, summary, severity = 'info', detailsJson = null) {
  try {
    const Database = requireBetterSqlite3();
    if (!Database) return false;
    if (!fs.existsSync(DB_PATH)) return false;

    const db = new Database(DB_PATH);
    const timestamp = new Date().toISOString();

    const stmt = db.prepare(`
      INSERT INTO activity_feed (timestamp, activity_type, actor, summary, severity, details_json)
      VALUES (?, ?, ?, ?, ?, ?)
    `);

    stmt.run(timestamp, activityType, actor, summary, severity, detailsJson);
    db.close();
    return true;
  } catch (err) {
    return false;
  }
}

function detectBuildCommand(command) {
  for (const { pattern, type } of BUILD_PATTERNS) {
    if (pattern.test(command)) return type;
  }
  return null;
}

function extractProjectName(command, cwd) {
  const slnMatch = command.match(/(\w+\.sln)/i);
  if (slnMatch) return slnMatch[1].replace('.sln', '');

  const csprojMatch = command.match(/(\w+\.csproj)/i);
  if (csprojMatch) return csprojMatch[1].replace('.csproj', '');

  if (cwd) return path.basename(cwd);
  return 'project';
}

function getToolSummary(tool, input) {
  if (!input) return tool;

  switch (tool) {
    case 'Bash':
      const cmd = input.command || '';
      return cmd.length > 60 ? cmd.substring(0, 60) + '...' : cmd;
    case 'Edit':
    case 'Write':
      return input.file_path ? path.basename(input.file_path) : tool;
    case 'Task':
      return input.description || input.subagent_type || 'subagent';
    default:
      return tool;
  }
}

async function main() {
  let input = '';
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  if (!input.trim()) return;

  let hookData;
  try {
    hookData = JSON.parse(input);
  } catch (err) {
    return;
  }

  const terminalName = process.env.MULTITERMINAL_NAME || 'Unknown';
  const hookType = hookData.hook_type || hookData.type;
  const tool = hookData.tool || hookData.tool_name || '';

  switch (hookType) {
    case 'PreToolUse': {
      if (SKIP_TOOLS.has(tool)) break;
      const summary = getToolSummary(tool, hookData.input);
      recordActivity('TOOL_START', terminalName, `\${tool}: \${summary}`, 'info',
        JSON.stringify({ tool, input: hookData.input }));
      break;
    }

    case 'PostToolUse': {
      if (tool === 'Bash') {
        const command = hookData.input?.command || '';
        const buildType = detectBuildCommand(command);

        if (buildType) {
          const exitCode = hookData.output?.exit_code ?? hookData.exit_code ?? 0;
          const success = exitCode === 0;
          const projectName = extractProjectName(command, hookData.cwd);

          const activityType = success ? 'BUILD_SUCCEEDED' : 'BUILD_FAILED';
          const summary = success ? `Build succeeded: \${projectName}` : `Build failed: \${projectName}`;
          const severity = success ? 'info' : 'error';

          recordActivity(activityType, terminalName, summary, severity,
            JSON.stringify({ buildType, projectName, exitCode }));
          break;
        }
      }

      if (SKIP_TOOLS.has(tool)) break;
      const summary = getToolSummary(tool, hookData.input);
      recordActivity('TOOL_COMPLETE', terminalName, `\${tool}: \${summary}`, 'info',
        JSON.stringify({ tool }));
      break;
    }

    case 'PostToolUseFailure': {
      const error = hookData.error || hookData.output?.error || 'Unknown error';
      const summary = `\${tool} failed: \${error.substring(0, 100)}`;
      recordActivity('TOOL_FAILED', terminalName, summary, 'error',
        JSON.stringify({ tool, error }));
      break;
    }

    case 'SubagentStart': {
      const agentType = hookData.subagent_type || hookData.agent_type || 'unknown';
      const description = hookData.description || hookData.prompt?.substring(0, 50) || '';
      recordActivity('SUBAGENT_START', terminalName, `Started \${agentType}: \${description}`, 'info',
        JSON.stringify({ agentType, description }));
      break;
    }

    case 'SubagentStop': {
      const agentType = hookData.subagent_type || hookData.agent_type || 'unknown';
      const success = hookData.success !== false;
      const activityType = success ? 'SUBAGENT_COMPLETE' : 'SUBAGENT_FAILED';
      const severity = success ? 'info' : 'warning';
      recordActivity(activityType, terminalName, `\${agentType} \${success ? 'completed' : 'failed'}`, severity,
        JSON.stringify({ agentType, success }));
      break;
    }
  }
}

main().catch(() => {});
"@

$activityHookPath = Join-Path $HooksDir "activity-hook.js"
$activityHookContent | Out-File -FilePath $activityHookPath -Encoding UTF8 -Force
Write-Host "  ✓ Generated activity-hook.js" -ForegroundColor Green

# pool-context.js
$poolContextContent = @"
#!/usr/bin/env node
/**
 * Plan Context Injection Hook for Claude Code SessionStart
 * Auto-generated by Install-MultiTerminalIntegration.ps1
 */

const path = require('path');
const fs = require('fs');

function requireBetterSqlite3() {
  const possiblePaths = [
    'better-sqlite3',
    '$sqlite3PathEscaped',
  ];

  for (const modulePath of possiblePaths) {
    try {
      return require(modulePath);
    } catch (e) {
      // Try next path
    }
  }
  return null;
}

function getKanbanContext(db, terminalName) {
  const tableCheck = db.prepare(`
    SELECT name FROM sqlite_master
    WHERE type='table' AND name='tasks'
  `).get();

  if (!tableCheck) return null;

  const lines = [];

  if (terminalName) {
    const myTasks = db.prepare(`
      SELECT id, title, description, status, created_by, assignee
      FROM tasks
      WHERE assignee = ? AND status IN ('in_progress', 'todo')
      ORDER BY
        CASE status WHEN 'in_progress' THEN 0 WHEN 'todo' THEN 1 END,
        id
    `).all(terminalName);

    if (myTasks.length > 0) {
      lines.push(`## Your Kanban Tasks (\${terminalName})`);
      for (const task of myTasks) {
        const statusIcon = task.status === 'in_progress' ? '🔨' : '📋';
        lines.push(`\${statusIcon} [\${task.id}] \${task.title} (\${task.status})`);
        if (task.description) {
          const desc = task.description.split('\\n')[0].substring(0, 80);
          lines.push(`   \${desc}\${task.description.length > 80 ? '...' : ''}`);
        }
      }
      lines.push('');
      lines.push('Use list_tasks to see all board tasks, update_task_status when done.');
    }
  }

  if (lines.length === 0) {
    const availableTasks = db.prepare(`
      SELECT id, title, status, created_by
      FROM tasks
      WHERE (assignee IS NULL OR assignee = '') AND status IN ('todo', 'suggestion')
      ORDER BY
        CASE status WHEN 'todo' THEN 0 WHEN 'suggestion' THEN 1 END,
        id
      LIMIT 5
    `).all();

    if (availableTasks.length > 0) {
      lines.push('## Kanban Board - Available Tasks');
      for (const task of availableTasks) {
        const statusIcon = task.status === 'todo' ? '📋' : '💡';
        lines.push(`\${statusIcon} [\${task.id}] \${task.title} (\${task.status})`);
      }
      lines.push('');
      lines.push('Use claim_task(task_id, your_name) to claim a task.');
    } else {
      lines.push('## Kanban Board');
      lines.push('No tasks available to claim. Use create_task to add work items.');
    }
  }

  return lines.length > 0 ? lines.join('\\n') : null;
}

function getPlanContext() {
  try {
    const Database = requireBetterSqlite3();
    if (!Database) return null;

    const dbPath = path.join(process.env.APPDATA || '', 'multiterminal', 'multiterminal.db');
    if (!fs.existsSync(dbPath)) return null;

    const db = new Database(dbPath, { readonly: true });
    const terminalName = process.env.MULTITERMINAL_NAME;
    const lines = [];

    const kanbanContext = getKanbanContext(db, terminalName);
    if (kanbanContext) {
      lines.push(kanbanContext);
    }

    const tableCheck = db.prepare(`
      SELECT name FROM sqlite_master
      WHERE type='table' AND name='plans'
    `).get();

    if (tableCheck) {
      const plan = db.prepare(`
        SELECT id, title, description, current_phase, status, leader_id
        FROM plans
        WHERE status = 'active'
        LIMIT 1
      `).get();

      if (plan) {
        const phases = db.prepare(`
          SELECT id, phase_name, phase_order, checklist_json, started_at, completed_at
          FROM plan_phases
          WHERE plan_id = ?
          ORDER BY phase_order
        `).all(plan.id);

        let assignment = null;
        if (terminalName) {
          assignment = db.prepare(`
            SELECT id, role, assigned_task_summary, status, blocked_by
            FROM plan_assignments
            WHERE plan_id = ? AND terminal_name = ?
          `).get(plan.id, terminalName);
        }

        lines.push('');
        const phaseIndex = phases.findIndex(p => p.phase_name === plan.current_phase);
        lines.push(`## Active Plan: \${plan.title}`);
        lines.push(`Phase: \${plan.current_phase} (\${phaseIndex + 1}/\${phases.length}) | Leader: \${plan.leader_id || 'Unassigned'}`);

        if (assignment) {
          lines.push(`Your Role: \${assignment.role}`);
          lines.push(`Your Task: \${assignment.assigned_task_summary || 'Not specified'}`);
          lines.push(`Status: \${assignment.status}`);
          if (assignment.blocked_by) {
            lines.push(`Blocked By: \${assignment.blocked_by}`);
          }
        }

        const currentPhase = phases.find(p => p.phase_name === plan.current_phase);
        if (currentPhase && currentPhase.checklist_json) {
          try {
            const checklist = JSON.parse(currentPhase.checklist_json);
            if (checklist.length > 0) {
              lines.push('');
              lines.push('Checklist:');
              for (const item of checklist) {
                const mark = item.Done ? 'x' : ' ';
                lines.push(`  [\${mark}] \${item.Item}`);
              }
            }
          } catch (e) {
            // Ignore JSON parse errors
          }
        }
      }
    }

    db.close();

    if (lines.length === 0) {
      return '## Kanban Board\\nNo tasks found. Use create_task to add work items or list_tasks to check the board.';
    }

    return lines.join('\\n');

  } catch (e) {
    return null;
  }
}

function main() {
  const planContext = getPlanContext();
  if (planContext) {
    console.log(planContext);
  }
}

main();
"@

$poolContextPath = Join-Path $HooksDir "pool-context.js"
$poolContextContent | Out-File -FilePath $poolContextPath -Encoding UTF8 -Force
Write-Host "  ✓ Generated pool-context.js" -ForegroundColor Green

Write-Host ""

# === Step 5: Configure hooks.json ===
Write-Host "[5/7] Configuring hooks..." -ForegroundColor Green

$hooksJsonPath = Join-Path $ClaudeDir "hooks.json"
$activityHookPathEscaped = $activityHookPath.Replace('\', '\\')
$poolContextPathEscaped = $poolContextPath.Replace('\', '\\')

$hooksConfig = @{
    SessionStart = @{
        command = "node"
        args = @($poolContextPathEscaped)
        injectAs = "user-prompt-prefix"
    }
    PreToolUse = @{
        command = "node"
        args = @($activityHookPathEscaped)
    }
    PostToolUse = @{
        command = "node"
        args = @($activityHookPathEscaped)
    }
    PostToolUseFailure = @{
        command = "node"
        args = @($activityHookPathEscaped)
    }
    SubagentStart = @{
        command = "node"
        args = @($activityHookPathEscaped)
    }
    SubagentStop = @{
        command = "node"
        args = @($activityHookPathEscaped)
    }
}

# Merge with existing hooks if present
if (Test-Path $hooksJsonPath) {
    Write-Host "  ! Existing hooks.json found - backing up..." -ForegroundColor Yellow
    Copy-Item $hooksJsonPath "$hooksJsonPath.backup" -Force
    Write-Host "    Backup saved: $hooksJsonPath.backup" -ForegroundColor Gray
}

$hooksConfig | ConvertTo-Json -Depth 10 | Out-File -FilePath $hooksJsonPath -Encoding UTF8 -Force
Write-Host "  ✓ Configured hooks.json" -ForegroundColor Green

Write-Host ""

# === Step 6: Configure MCP servers ===
Write-Host "[6/7] Configuring MCP servers..." -ForegroundColor Green

$mcpServersPath = Join-Path $ClaudeDir "mcp_servers.json"
$mcpIndexPathEscaped = (Join-Path $McpServerDir "index.js").Replace('\', '\\')
$sessionsDbPathEscaped = (Join-Path $ClaudeDir "sessions.db").Replace('\', '\\')

$mcpConfig = @{
    mcpServers = @{
        "mcp-session-history" = @{
            command = "node"
            args = @($mcpIndexPathEscaped)
            env = @{
                SESSIONS_DB_PATH = $sessionsDbPathEscaped
            }
        }
    }
}

# Merge with existing MCP servers if present
if (Test-Path $mcpServersPath) {
    Write-Host "  ! Existing mcp_servers.json found - backing up..." -ForegroundColor Yellow
    Copy-Item $mcpServersPath "$mcpServersPath.backup" -Force
    Write-Host "    Backup saved: $mcpServersPath.backup" -ForegroundColor Gray

    try {
        $existing = Get-Content $mcpServersPath -Raw | ConvertFrom-Json

        # Merge MCP servers
        if ($existing.mcpServers) {
            foreach ($key in $existing.mcpServers.PSObject.Properties.Name) {
                if ($key -ne "mcp-session-history") {
                    $mcpConfig.mcpServers[$key] = $existing.mcpServers.$key
                }
            }
        }

        Write-Host "    Merged with existing configuration" -ForegroundColor Gray
    } catch {
        Write-Warning "  Could not parse existing mcp_servers.json - overwriting"
    }
}

$mcpConfig | ConvertTo-Json -Depth 10 | Out-File -FilePath $mcpServersPath -Encoding UTF8 -Force
Write-Host "  ✓ Configured mcp_servers.json" -ForegroundColor Green

Write-Host ""

# === Step 7: Validation ===
Write-Host "[7/7] Validating installation..." -ForegroundColor Green

$allValid = $true

# Check hooks
if (Test-Path $activityHookPath) {
    Write-Host "  ✓ activity-hook.js installed" -ForegroundColor Green
} else {
    Write-Host "  ✗ activity-hook.js missing" -ForegroundColor Red
    $allValid = $false
}

if (Test-Path $poolContextPath) {
    Write-Host "  ✓ pool-context.js installed" -ForegroundColor Green
} else {
    Write-Host "  ✗ pool-context.js missing" -ForegroundColor Red
    $allValid = $false
}

# Check config files
if (Test-Path $hooksJsonPath) {
    Write-Host "  ✓ hooks.json configured" -ForegroundColor Green
} else {
    Write-Host "  ✗ hooks.json missing" -ForegroundColor Red
    $allValid = $false
}

if (Test-Path $mcpServersPath) {
    Write-Host "  ✓ mcp_servers.json configured" -ForegroundColor Green
} else {
    Write-Host "  ✗ mcp_servers.json missing" -ForegroundColor Red
    $allValid = $false
}

# Check MCP server
$mcpIndexPath = Join-Path $McpServerDir "index.js"
if (Test-Path $mcpIndexPath) {
    Write-Host "  ✓ MCP server available" -ForegroundColor Green
} else {
    Write-Host "  ✗ MCP server missing" -ForegroundColor Red
    $allValid = $false
}

# Check better-sqlite3
$sqlite3ModulePath = Join-Path $McpServerDir "node_modules\better-sqlite3"
if (Test-Path $sqlite3ModulePath) {
    Write-Host "  ✓ better-sqlite3 installed" -ForegroundColor Green
} else {
    Write-Host "  ✗ better-sqlite3 missing (run with -SkipNodeModules:$false)" -ForegroundColor Red
    $allValid = $false
}

Write-Host ""

if ($allValid) {
    Write-Host "=== Installation Complete! ===" -ForegroundColor Green
    Write-Host ""
    Write-Host "MultiTerminal integration is ready. Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Restart Claude Code CLI if it's running"
    Write-Host "  2. Launch MultiTerminal.exe"
    Write-Host "  3. Open a new Claude Code session"
    Write-Host "  4. Hooks will automatically activate"
    Write-Host ""
    Write-Host "Configuration:" -ForegroundColor Yellow
    Write-Host "  Hooks:       $HooksDir"
    Write-Host "  MCP Config:  $mcpServersPath"
    Write-Host "  Database:    $DataDir\multiterminal.db"
} else {
    Write-Host "=== Installation Failed ===" -ForegroundColor Red
    Write-Host ""
    Write-Host "Some components are missing. Please review the errors above." -ForegroundColor Red
    exit 1
}
