using System;
using System.Collections.Generic;

namespace MultiTerminal.MCPServer.Models
{
    /// <summary>
    /// Represents a notification message in a user's inbox.
    /// Auto-generated by checklist state transitions and escalation events.
    /// </summary>
    public class InboxMessage
    {
        /// <summary>
        /// Unique message identifier (8-char GUID).
        /// </summary>
        public string Id { get; set; } = Guid.NewGuid().ToString("N").Substring(0, 8);

        /// <summary>
        /// Recipient user (matches TeamMemberProfile.Id or terminal name).
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Related kanban task ID.
        /// </summary>
        public string TaskId { get; set; }

        /// <summary>
        /// Related kanban task title (denormalized for display).
        /// </summary>
        public string TaskTitle { get; set; }

        /// <summary>
        /// Related checklist item index (null if task-level notification).
        /// </summary>
        public int? ChecklistItemIndex { get; set; }

        /// <summary>
        /// Checklist item name (denormalized for display).
        /// </summary>
        public string ChecklistItemName { get; set; }

        /// <summary>
        /// Notification type: "ready_for_testing", "escalation", "task_complete", "helper_request".
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Short summary of what happened and what needs attention.
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// When the notification was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Who triggered the notification (agent/terminal name).
        /// </summary>
        public string CreatedBy { get; set; }

        /// <summary>
        /// When the message was read (null = unread).
        /// </summary>
        public DateTime? ReadAt { get; set; }

        /// <summary>
        /// Reply text from the user (null if no reply).
        /// </summary>
        public string ReplyText { get; set; }

        /// <summary>
        /// When the reply was sent (null if no reply).
        /// </summary>
        public DateTime? RepliedAt { get; set; }
    }

    /// <summary>
    /// Result of retrieving inbox messages.
    /// </summary>
    public class GetInboxResult
    {
        public bool Success { get; set; }
        public List<InboxMessage> Messages { get; set; } = new List<InboxMessage>();
        public int UnreadCount { get; set; }
        public int TotalCount { get; set; }
        public string Error { get; set; }
    }

    /// <summary>
    /// Result of marking an inbox message as read.
    /// </summary>
    public class MarkInboxReadResult
    {
        public bool Success { get; set; }
        public string Error { get; set; }
    }

    /// <summary>
    /// Result of replying to an inbox message.
    /// </summary>
    public class ReplyToInboxResult
    {
        public bool Success { get; set; }
        public string Error { get; set; }
    }

    /// <summary>
    /// Result of creating an inbox message.
    /// </summary>
    public class CreateInboxMessageResult
    {
        public bool Success { get; set; }
        public string MessageId { get; set; }
        public string Error { get; set; }
    }
}
