using System;

namespace MultiTerminal.MCPServer.Models
{
    /// <summary>
    /// Represents a progress summary for a task, capturing context at status changes.
    /// </summary>
    public class TaskSummary
    {
        public int Id { get; set; }
        public string TaskId { get; set; }
        public DateTime SummaryAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// What triggered this summary: 'status_change', 'checkpoint', 'session_end'
        /// </summary>
        public string TriggeredBy { get; set; }

        public string PreviousStatus { get; set; }
        public string NewStatus { get; set; }

        /// <summary>
        /// Description of work completed so far.
        /// </summary>
        public string WorkCompleted { get; set; }

        /// <summary>
        /// What needs to be done next.
        /// </summary>
        public string NextSteps { get; set; }

        /// <summary>
        /// Any blockers preventing progress.
        /// </summary>
        public string Blockers { get; set; }

        /// <summary>
        /// Additional notes or context.
        /// </summary>
        public string Notes { get; set; }

        /// <summary>
        /// Terminal name that created this summary.
        /// </summary>
        public string Author { get; set; }

        /// <summary>
        /// True if this summary was auto-generated from context.
        /// Auto-generated summaries are prefixed with [Auto] in display.
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        /// <summary>
        /// True if this summary is pending enhancement by the terminal.
        /// Pending summaries can be enhanced before the next status change.
        /// </summary>
        public bool PendingEnhancement { get; set; }

        /// <summary>
        /// Get display prefix based on auto-generation and pending status.
        /// </summary>
        public string DisplayPrefix => PendingEnhancement ? "[Auto - Draft] " : (IsAutoGenerated ? "[Auto] " : "");
    }
}
