using System;
using System.IO;
using System.Text;

namespace MultiTerminal.Services
{
    /// <summary>
    /// Ensures a Codex-facing <c>AGENTS.md</c> exists at the project root so Codex
    /// picks up project context on launch. Translates from <c>.claude/CLAUDE.md</c>
    /// when present; otherwise writes a minimal stub. Write-once: respects user
    /// edits on subsequent launches. To refresh, the user deletes the file.
    /// </summary>
    public static class CodexAgentsService
    {
        /// <summary>
        /// Writes <c>{projectRoot}/AGENTS.md</c> if it does not already exist.
        /// Safe to call on every Codex launch — no-op when the file is present.
        /// Returns the absolute path written, or null if nothing was written
        /// (file exists, project root invalid, or another launch beat us to it).
        ///
        /// Concurrent-safe: uses <c>FileMode.CreateNew</c> so two first-launches
        /// race cleanly. The loser's <c>IOException</c> is swallowed because the
        /// winner's content is already on disk by then.
        ///
        /// Callers should only pass a validated project root — see the home-dir
        /// guard in <c>LaunchCommandBuilder.BuildCodexCommand</c> which avoids
        /// planting an AGENTS.md in the user profile when
        /// <c>ResolveWorkingDirectory</c> falls back.
        /// </summary>
        public static string EnsureAgentsMd(string projectRoot, string projectName = null)
        {
            if (string.IsNullOrWhiteSpace(projectRoot) || !Directory.Exists(projectRoot))
                return null;

            string agentsPath = Path.Combine(projectRoot, "AGENTS.md");
            if (File.Exists(agentsPath))
                return null;

            string claudeMdPath = Path.Combine(projectRoot, ".claude", "CLAUDE.md");
            string content;
            if (File.Exists(claudeMdPath))
            {
                string claudeContent = File.ReadAllText(claudeMdPath);
                content = BuildTranslatedAgentsMd(claudeContent);
            }
            else
            {
                string derivedName = projectName;
                if (string.IsNullOrWhiteSpace(derivedName))
                    derivedName = Path.GetFileName(projectRoot.TrimEnd('\\', '/'));
                if (string.IsNullOrWhiteSpace(derivedName))
                    derivedName = "(unnamed)";
                content = BuildStubAgentsMd(derivedName);
            }

            try
            {
                // Concurrent-safe write-once: see CodexPromptService.WriteOnce for the
                // same pattern. Kept inline here because EnsureAgentsMd needs a
                // null-return on the race-lost path where WriteOnce returns void.
                using var fs = new FileStream(agentsPath, FileMode.CreateNew, FileAccess.Write, FileShare.Read);
                byte[] bytes = Encoding.UTF8.GetBytes(content);
                fs.Write(bytes, 0, bytes.Length);
            }
            catch (IOException) when (File.Exists(agentsPath))
            {
                // Concurrent launch got there first. Their content is on disk.
                return null;
            }

            return agentsPath;
        }

        private static string BuildTranslatedAgentsMd(string claudeContent)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# AGENTS.md");
            sb.AppendLine();
            sb.AppendLine("> Codex-facing copy of `.claude/CLAUDE.md` generated by MultiTerminal on first Codex launch.");
            sb.AppendLine("> Treat `.claude/CLAUDE.md` as the source of truth — delete this file and relaunch to regenerate.");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
            sb.Append(claudeContent);
            if (!claudeContent.EndsWith('\n'))
                sb.AppendLine();
            return sb.ToString();
        }

        private static string BuildStubAgentsMd(string projectName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# AGENTS.md");
            sb.AppendLine();
            sb.AppendLine($"Project: **{projectName}**");
            sb.AppendLine();
            sb.AppendLine("This project was launched from MultiTerminal. You are a team member — register with");
            sb.AppendLine("the `multiterminal` MCP server (via `register_terminal`) on startup and coordinate");
            sb.AppendLine("with other terminals via the messaging tools.");
            sb.AppendLine();
            sb.AppendLine("Add project-specific instructions to this file, or create `.claude/CLAUDE.md` and");
            sb.AppendLine("delete this file — MultiTerminal will regenerate AGENTS.md from CLAUDE.md on the");
            sb.AppendLine("next Codex launch.");
            sb.AppendLine();
            return sb.ToString();
        }
    }
}
