using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MultiTerminal.MCPServer.Models;
using MultiTerminal.Services;

namespace MultiTerminal.MCPServer.Services
{
    /// <summary>
    /// Service for managing task progress summaries.
    /// Handles auto-generation and persistence of context summaries.
    /// Supports Fast mode (tool-based context) and enhanced intelligence.
    /// </summary>
    public class SummaryService
    {
        private readonly TaskDatabase _taskDb;
        private readonly ActivityService _activityService;
        private readonly ActivityFeedService _activityFeedService;

        public SummaryService(
            TaskDatabase taskDb,
            ActivityService activityService,
            ActivityFeedService activityFeedService)
        {
            _taskDb = taskDb;
            _activityService = activityService;
            _activityFeedService = activityFeedService;
        }

        /// <summary>
        /// Auto-generate a summary when task status changes.
        /// Uses Fast mode context extraction for intelligent summary generation.
        /// </summary>
        /// <param name="taskId">The task ID</param>
        /// <param name="taskTitle">The task title for context</param>
        /// <param name="previousStatus">Previous status before change</param>
        /// <param name="newStatus">New status after change</param>
        /// <param name="author">Terminal making the change</param>
        /// <param name="activityDescription">Optional activity description for context</param>
        /// <param name="useFastMode">Use Fast mode (tool-based context). Default true.</param>
        /// <returns>The generated summary</returns>
        public TaskSummary AutoGenerateSummary(
            string taskId,
            string taskTitle,
            string previousStatus,
            string newStatus,
            string author,
            string activityDescription = null,
            bool useFastMode = true)
        {
            // Finalize any pending summaries for this task before creating new one
            FinalizePendingSummaries(taskId);

            var summary = new TaskSummary
            {
                TaskId = taskId,
                SummaryAt = DateTime.UtcNow,
                TriggeredBy = "status_change",
                PreviousStatus = previousStatus,
                NewStatus = newStatus,
                Author = author,
                IsAutoGenerated = true,
                PendingEnhancement = true  // Mark as draft, can be enhanced before next status change
            };

            // Extract context if Fast mode enabled
            SummaryContext context = null;
            if (useFastMode)
            {
                // Look back 30 minutes for relevant activity
                var since = DateTime.UtcNow.AddMinutes(-30);
                context = ExtractContext(taskId, author, since);
            }

            // Generate work_completed based on status transition and context
            summary.WorkCompleted = GenerateWorkCompletedText(
                previousStatus, newStatus, taskTitle, activityDescription, context);

            // Generate next_steps based on new status and context
            summary.NextSteps = GenerateNextStepsText(newStatus, taskTitle, context);

            // Add blockers if detected from context
            if (context != null && context.CurrentStatus == "blocked")
            {
                summary.Blockers = context.CurrentActivity ?? "Blocked (details not specified)";
            }

            // Save to database
            _taskDb.SaveTaskSummary(summary);

            return summary;
        }

        /// <summary>
        /// Create a manual summary (checkpoint or explicit save).
        /// </summary>
        public TaskSummary CreateManualSummary(
            string taskId,
            string triggeredBy,
            string workCompleted,
            string nextSteps,
            string blockers,
            string notes,
            string author)
        {
            var summary = new TaskSummary
            {
                TaskId = taskId,
                SummaryAt = DateTime.UtcNow,
                TriggeredBy = triggeredBy,
                WorkCompleted = workCompleted,
                NextSteps = nextSteps,
                Blockers = blockers,
                Notes = notes,
                Author = author,
                IsAutoGenerated = false
            };

            _taskDb.SaveTaskSummary(summary);
            return summary;
        }

        /// <summary>
        /// Get summaries for a task.
        /// </summary>
        public List<TaskSummary> GetTaskSummaries(string taskId, int limit = 10)
        {
            return _taskDb.GetTaskSummaries(taskId, limit);
        }

        /// <summary>
        /// Get the latest summary for a task.
        /// </summary>
        public TaskSummary GetLatestSummary(string taskId)
        {
            return _taskDb.GetLatestSummary(taskId);
        }

        /// <summary>
        /// Get recent summaries across all tasks.
        /// </summary>
        public List<TaskSummary> GetAllRecentSummaries(int limit = 20)
        {
            return _taskDb.GetAllRecentSummaries(limit);
        }

        #region Enhancement Management

        /// <summary>
        /// Finalize any pending summaries for a task.
        /// Called when a new summary is created to finalize the previous draft.
        /// </summary>
        private void FinalizePendingSummaries(string taskId)
        {
            _taskDb.FinalizePendingSummaries(taskId);
        }

        /// <summary>
        /// Get pending summaries for a task that are awaiting enhancement.
        /// </summary>
        public List<TaskSummary> GetPendingSummaries(string taskId)
        {
            return _taskDb.GetPendingSummaries(taskId);
        }

        #endregion

        #region Context Extraction (Fast Mode)

        /// <summary>
        /// Extract rich context for summary generation (Fast mode).
        /// Gathers activity events, tool usage, builds, and recent activity.
        /// </summary>
        private SummaryContext ExtractContext(string taskId, string terminalName, DateTime since)
        {
            var context = new SummaryContext();

            // Get previous summary for continuity
            var previousSummary = _taskDb.GetLatestSummary(taskId);
            if (previousSummary != null)
            {
                context.PreviousWorkCompleted = previousSummary.WorkCompleted;
                context.PreviousNextSteps = previousSummary.NextSteps;
            }

            // Get recent activity events for this terminal
            try
            {
                var recentEvents = _activityFeedService?.GetActivitiesSince(since, limit: 20);
                if (recentEvents != null)
                {
                    // Filter for events related to this terminal
                    context.ToolEvents = recentEvents
                        .Where(e => e.Actor == terminalName &&
                               (e.ActivityType == "TOOL_COMPLETE" || e.ActivityType == "TOOL_FAILED"))
                        .Select(e => e.Summary)
                        .ToList();

                    context.BuildEvents = recentEvents
                        .Where(e => e.Actor == terminalName &&
                               (e.ActivityType == "BUILD_SUCCEEDED" || e.ActivityType == "BUILD_FAILED"))
                        .Select(e => e.Summary)
                        .ToList();

                    context.SubagentEvents = recentEvents
                        .Where(e => e.Actor == terminalName &&
                               (e.ActivityType == "SUBAGENT_COMPLETE" || e.ActivityType == "SUBAGENT_FAILED"))
                        .Select(e => e.Summary)
                        .ToList();
                }
            }
            catch
            {
                // If activity feed service unavailable, continue without it
            }

            // Get current terminal activity
            try
            {
                var terminalActivity = _activityService?.GetActivity(terminalName);
                if (terminalActivity != null)
                {
                    context.CurrentActivity = terminalActivity.Activity;
                    context.CurrentStatus = terminalActivity.Status;
                }
            }
            catch
            {
                // If activity service unavailable, continue without it
            }

            return context;
        }

        /// <summary>
        /// Internal class for holding extracted context.
        /// </summary>
        private class SummaryContext
        {
            public string PreviousWorkCompleted { get; set; }
            public string PreviousNextSteps { get; set; }
            public List<string> ToolEvents { get; set; } = new List<string>();
            public List<string> BuildEvents { get; set; } = new List<string>();
            public List<string> SubagentEvents { get; set; } = new List<string>();
            public string CurrentActivity { get; set; }
            public string CurrentStatus { get; set; }
        }

        #endregion

        private string GenerateWorkCompletedText(
            string previousStatus,
            string newStatus,
            string taskTitle,
            string activityDescription,
            SummaryContext context)
        {
            // Use activity description if provided
            if (!string.IsNullOrEmpty(activityDescription))
            {
                return activityDescription;
            }

            // Build context-aware summary
            var parts = new List<string>();

            // Base transition text
            if (newStatus == "done")
            {
                parts.Add($"Completed '{taskTitle}'");
            }
            else if (previousStatus == "in_progress" && newStatus == "todo")
            {
                parts.Add($"Paused '{taskTitle}'");
            }
            else if (newStatus == "in_progress" && previousStatus == "todo")
            {
                parts.Add($"Started '{taskTitle}'");
            }
            else if (previousStatus == "in_progress")
            {
                parts.Add($"Working on '{taskTitle}'");
            }
            else
            {
                parts.Add($"Updated '{taskTitle}'");
            }

            // Add context if available
            if (context != null)
            {
                var contextDetails = new List<string>();

                // Add tool usage
                if (context.ToolEvents.Any())
                {
                    var toolCount = context.ToolEvents.Count;
                    contextDetails.Add($"{toolCount} tool{(toolCount > 1 ? "s" : "")} used");
                }

                // Add build status
                if (context.BuildEvents.Any())
                {
                    var buildSummary = context.BuildEvents.First(); // Most recent
                    contextDetails.Add(buildSummary.ToLowerInvariant());
                }

                // Add subagent work
                if (context.SubagentEvents.Any())
                {
                    var subagentCount = context.SubagentEvents.Count;
                    contextDetails.Add($"{subagentCount} subagent{(subagentCount > 1 ? "s" : "")} completed");
                }

                if (contextDetails.Any())
                {
                    parts.Add($"({string.Join(", ", contextDetails)})");
                }
            }

            return string.Join(" ", parts);
        }

        private string GenerateNextStepsText(string newStatus, string taskTitle, SummaryContext context)
        {
            if (newStatus == "done")
            {
                return "Task completed - no further action needed";
            }

            // Use context to provide smarter next steps
            if (context != null)
            {
                // If there were build failures, suggest fixing them
                if (context.BuildEvents.Any(e => e.ToLowerInvariant().Contains("failed")))
                {
                    return "Fix build errors before proceeding";
                }

                // If previous next steps exist, reference them
                if (!string.IsNullOrEmpty(context.PreviousNextSteps) &&
                    context.PreviousNextSteps != "Continue working on task")
                {
                    return context.PreviousNextSteps; // Continue with previous plan
                }
            }

            // Fallback to status-based next steps
            if (newStatus == "todo")
            {
                return "Ready to be picked up when available";
            }
            else if (newStatus == "in_progress")
            {
                return "Continue working on task";
            }

            return null;
        }
    }
}
