/**
 * MultiTerminal Post-Install Script
 *
 * Runs after Inno Setup copies files. Handles:
 * 1. Setting CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS env in ~/.claude/settings.json
 * 2. OPT-IN (--global-reg=yes, GH#2): registering MCP servers in ~/.claude.json so
 *    Claude Code sessions started OUTSIDE MultiTerminal see them. MT-spawned terminals
 *    never need this — the app regenerates %APPDATA%\multiterminal\.mcp.json at startup
 *    (GatewayIntegrationService.EnsureMcpConfig) and passes it per-launch via --mcp-config
 *    (LaunchCommandBuilder), along with the plugin via --plugin-dir.
 * 3. Writing gateway-defaults.json for optional MCP servers (gateway auto-seeds on startup)
 * 4. Patching runtimeconfig.json for framework-dependent mode (if .NET 8 detected)
 *
 * Note: hooks, agents, skills, and CLAUDE.md live in the Claude Code plugin at
 *   %USERPROFILE%\.claude\plugins\marketplaces\multiterminal-marketplace\plugins\multiterminal\
 * The installer always copies the plugin marketplace as a unit — it is the SOURCE that
 * --plugin-dir points at, so it is required even when global registration is off. A copied
 * marketplace does NOT load the plugin into non-MT sessions (that requires enabledPlugins
 * or --plugin-dir).
 *
 * Usage: node post-install.js <installDir> <appDataDir> <userProfileDir> [--framework-dependent|--self-contained] [--mcps=name1,name2,...] [--global-reg=yes|no]
 */

const fs = require('fs');
const path = require('path');

const installDir = process.argv[2];
const appDataDir = process.argv[3];
const userProfileDir = process.argv[4];
const dotnetFlag = process.argv[5] || '--self-contained';
const mcpsFlag = process.argv[6] || '--mcps=none';
const globalRegFlag = process.argv[7] || '--global-reg=no';

if (!installDir || !appDataDir || !userProfileDir) {
    console.error('Usage: node post-install.js <installDir> <appDataDir> <userProfileDir> [--framework-dependent|--self-contained] [--mcps=name1,name2,...]');
    process.exit(1);
}

const isFrameworkDependent = (dotnetFlag === '--framework-dependent');
const selectedMcps = mcpsFlag.replace('--mcps=', '').split(',').filter(m => m && m !== 'none');
const globalRegistration = (globalRegFlag === '--global-reg=yes');
const claudeGlobalDir = path.join(userProfileDir, '.claude');

function ensureDir(dir) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// ============================================================
// 1. Enable experimental agent teams via ~/.claude/settings.json
//    Required for Team Agents / AgentPanel.
// ============================================================
function setExperimentalAgentTeamsEnv() {
    const settingsPath = path.join(claudeGlobalDir, 'settings.json');

    let settings = {};
    if (fs.existsSync(settingsPath)) {
        try {
            const backupPath = settingsPath + '.pre-multiterminal.bak';
            fs.copyFileSync(settingsPath, backupPath);
            settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
        } catch (e) {
            console.warn('Warning: Could not parse existing settings.json, creating new one');
            settings = {};
        }
    }

    if (!settings.env) {
        settings.env = {};
    }
    settings.env.CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1";

    ensureDir(claudeGlobalDir);
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
    console.log(`Set CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 in: ${settingsPath}`);
}

// ============================================================
// 2. Register MCP servers in ~/.claude.json (user-level config)
//    OPT-IN via --global-reg=yes (the claude\globalreg installer
//    component, GH#2). Only needed for Claude Code sessions started
//    outside MultiTerminal — MT-spawned terminals get the servers
//    per-launch via --mcp-config (%APPDATA%\multiterminal\.mcp.json,
//    regenerated by the app at startup).
// ============================================================
function registerMcpServers() {
    if (!globalRegistration) {
        console.log('Global MCP registration: skipped (opt-in not selected).');
        console.log('  MT-spawned terminals load MCP servers via --mcp-config at launch.');
        console.log('  Re-run the installer and check "Register MCP servers globally" to enable.');
        return;
    }

    const claudeJsonPath = path.join(userProfileDir, '.claude.json');
    const mcpServerPath = path.join(appDataDir, 'multiterminal', 'mcp', 'index.js');
    const mcpGatewayPath = path.join(installDir, 'mcp-gateway', 'McpGateway.exe');

    // Use forward slashes for cross-platform compatibility
    const normalize = (p) => p.replace(/\\/g, '/');

    let claudeConfig = {};
    if (fs.existsSync(claudeJsonPath)) {
        try {
            // Back up before modifying
            const backupPath = claudeJsonPath + '.pre-multiterminal.bak';
            fs.copyFileSync(claudeJsonPath, backupPath);
            claudeConfig = JSON.parse(fs.readFileSync(claudeJsonPath, 'utf-8'));
        } catch (e) {
            console.error('Error: Could not parse ~/.claude.json. Aborting MCP registration.');
            console.error('  This file is critical — not safe to overwrite.');
            return;
        }
    } else {
        console.error('Error: ~/.claude.json not found. Claude Code must be installed first.');
        return;
    }

    if (!claudeConfig.mcpServers) {
        claudeConfig.mcpServers = {};
    }

    claudeConfig.mcpServers['mcp-gateway'] = {
        "type": "stdio",
        "command": normalize(mcpGatewayPath),
        "args": [],
        "env": {}
    };

    claudeConfig.mcpServers['multiterminal'] = {
        "type": "stdio",
        "command": "node",
        "args": [normalize(mcpServerPath)],
        "env": {}
    };

    fs.writeFileSync(claudeJsonPath, JSON.stringify(claudeConfig, null, 2), 'utf-8');
    console.log(`Registered MCP servers in: ${claudeJsonPath}`);

    // NOTE: do NOT delete %APPDATA%\multiterminal\.mcp.json here. It is not legacy —
    // the app regenerates it at startup and MT-spawned terminals load it via --mcp-config.
}

// ============================================================
// 3. Write gateway-defaults.json for optional MCP servers.
//    The gateway auto-seeds from this file on next startup.
// ============================================================
function registerOptionalMcps() {
    if (selectedMcps.length === 0) {
        console.log('No optional MCP servers selected.');
        return;
    }

    const mcpsDir = path.join(installDir, 'mcps');
    const normalize = (p) => p.replace(/\\/g, '/');

    const mcpDefs = {
        'mssql': {
            display_name: 'MSSQL',
            description: 'Microsoft SQL Server query and schema tools',
            command: 'node',
            args: [normalize(path.join(mcpsDir, 'mssql', 'dist', 'index.js'))],
            env: {
                MSSQL_SERVER: '${MSSQL_SERVER}',
                MSSQL_PORT: '${MSSQL_PORT:-1433}',
                MSSQL_DATABASE: '${MSSQL_DATABASE}',
                MSSQL_USER: '${MSSQL_USER}',
                MSSQL_PASSWORD: '${MSSQL_PASSWORD}',
                MSSQL_ENCRYPT: '${MSSQL_ENCRYPT:-false}',
                AI_PROVIDER: 'claude'
            }
        },
        'sqlite': {
            display_name: 'SQLite',
            description: 'Local SQLite database query and management tools',
            command: 'node',
            args: [normalize(path.join(mcpsDir, 'sqlite', 'custom-sqlite-mcp-server.js'))],
            env: {}
        },
        'windows-build-runner': {
            display_name: 'Windows Build Runner',
            description: 'MSBuild and dotnet build execution tools',
            command: 'node',
            args: [normalize(path.join(mcpsDir, 'windows-build-runner', 'build', 'index.js'))],
            env: {}
        },
        'windowssnapit': {
            display_name: 'Windows SnapIt',
            description: 'Window screenshot capture tools',
            command: 'node',
            args: [normalize(path.join(mcpsDir, 'windowssnapit', 'index.js'))],
            env: {}
        },
        'everything-search': {
            display_name: 'Everything Search',
            description: 'Instant file search via voidtools Everything',
            command: 'node',
            args: [normalize(path.join(mcpsDir, 'everything-search', 'build', 'index.js'))],
            env: {}
        }
    };

    ensureDir(path.join(appDataDir, 'multiterminal', 'gateway'));

    const defaultsPath = path.join(appDataDir, 'multiterminal', 'gateway', 'gateway-defaults.json');
    const defaultsConfig = {};
    for (const mcpName of selectedMcps) {
        const def = mcpDefs[mcpName];
        if (!def) {
            console.warn(`  Unknown MCP: ${mcpName}, skipping`);
            continue;
        }
        defaultsConfig[mcpName] = {
            display_name: def.display_name,
            description: def.description,
            transport_type: 'stdio',
            command: def.command,
            args: def.args,
            env: def.env,
            enabled: true
        };
    }
    fs.writeFileSync(defaultsPath, JSON.stringify(defaultsConfig, null, 2), 'utf-8');
    console.log(`  Wrote gateway defaults (${selectedMcps.length} servers): ${defaultsPath}`);
    console.log('  Servers will be registered when the gateway starts.');
}

// ============================================================
// 4. Patch runtimeconfig.json for framework-dependent mode
// ============================================================
function patchRuntimeConfig() {
    if (!isFrameworkDependent) {
        console.log('Self-contained mode: runtimeconfig.json unchanged.');
        return;
    }

    const rcPath = path.join(installDir, 'MultiTerminal.runtimeconfig.json');
    if (!fs.existsSync(rcPath)) {
        console.warn('Warning: runtimeconfig.json not found, skipping patch.');
        return;
    }

    try {
        const config = JSON.parse(fs.readFileSync(rcPath, 'utf-8'));

        if (config.runtimeOptions && config.runtimeOptions.includedFrameworks) {
            fs.copyFileSync(rcPath, rcPath + '.self-contained.bak');

            config.runtimeOptions.frameworks = config.runtimeOptions.includedFrameworks.map(fw => ({
                name: fw.name,
                version: fw.version.split('.').slice(0, 2).join('.') + '.0'
            }));
            delete config.runtimeOptions.includedFrameworks;

            fs.writeFileSync(rcPath, JSON.stringify(config, null, 2), 'utf-8');
            console.log('Patched runtimeconfig.json for framework-dependent mode.');
        } else {
            console.log('runtimeconfig.json already in framework-dependent mode.');
        }
    } catch (e) {
        console.warn(`Warning: Could not patch runtimeconfig.json: ${e.message}`);
    }
}

// ============================================================
// Run all steps
// ============================================================
try {
    console.log('MultiTerminal post-install configuration...');
    console.log(`  Install dir:    ${installDir}`);
    console.log(`  AppData dir:    ${appDataDir}`);
    console.log(`  User profile:   ${userProfileDir}`);
    console.log(`  .NET mode:      ${isFrameworkDependent ? 'framework-dependent' : 'self-contained'}`);
    console.log(`  Global MCP reg: ${globalRegistration ? 'yes (opt-in selected)' : 'no (default — MT terminals use --mcp-config)'}`);
    console.log('');

    setExperimentalAgentTeamsEnv();
    registerMcpServers();
    registerOptionalMcps();
    patchRuntimeConfig();

    console.log('');
    console.log('Claude Code integration configured successfully.');
    process.exit(0);
} catch (err) {
    console.error('Post-install error:', err.message);
    process.exit(0);
}
